# Project Setup
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod Properties
mod_version=1.0.0
maven_group=com.greekoasc.fakewindow
archives_base_name=fakewindow

# Fabric Environment for Minecraft 1.21
minecraft_version=1.21
yarn_mappings=1.21+build.4
loader_version=0.15.11
fabric_version=0.100.4+1.21

